name: Build Wheels

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.2
      env:
        CIBW_BUILD: cp310-* cp311-* cp312-* cp313-* cp314-*
        CIBW_SKIP: "*-musllinux_* *-win32"
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        # Install zstd in build container for compression support
        CIBW_BEFORE_ALL_LINUX: yum install -y zstd-devel || apt-get install -y libzstd-dev || true
        CIBW_BEFORE_BUILD: pip install setuptools wheel
        CIBW_TEST_REQUIRES: pytest
        CIBW_TEST_COMMAND: "pytest {project}/tests/unit"

    - uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: ./wheelhouse/*.whl
