name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build-wheels.yml

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pwalk
    permissions:
      id-token: write  # OIDC publishing

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: wheels
        path: dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # Uses OIDC trusted publishing - no API tokens needed
